name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    - name: Create local.properties file
      run: |
        echo "base.url=${{ secrets.BASE_URL }}" > ./local.properties
        echo "kakao.native.key=${{ secrets.KAKAO_NATIVE_APP_KEY }}" >> ./local.properties
        echo "google.oauth.key=${{ secrets.GOOGLE_OAUTH_KEY }}" >> ./local.properties

    - name: Verify local.properties content
      run: cat ./local.properties

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Clean Build
      run: ./gradlew clean
       
